version: '3'

volumes:
  bitcoind: {}
  prometheus: {}
  grafana: {}

services:
  bitcoind:
    image: exodusmovement/bitcoind:0.16.2-004
    container_name: bitcoind
    environment:
      - BITCOIND_ARGUMENTS=-disablewallet -printtoconsole -server -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0
    volumes:
      - bitcoind:/home/bitcoind/.bitcoin
      - ./bitcoind/bitcoin.conf:/home/bitcoind/.bitcoin/bitcoin.conf

  bitcoind-exporter:
    build:
      context: ../
    container_name: bitcoind-exporter
    environment:
      - BITCOIND_EXPORTER_NODE=http://bitcoinrpc:password@bitcoind:8332/
    depends_on:
      - bitcoind
    ports:
      - 8000:8000
    restart: always

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    depends_on:
      - bitcoind-exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:5.2.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
