{
 "title": "Bitcoind",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "bitcoind_version{name=\"btc1\"}"
    }
   ]
  },
  {
   "title": "Total sync",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bitcoind_blockchain_sync_progress{name=\"btc1\"}"
    }
   ]
  },
  {
   "title": "Peers versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "bitcoind_peers{name=\"btc1\"}"
    }
   ]
  },
  {
   "title": "Blockchain size on disk in MiB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoind_blockchain_size_bytes{name=\"btc1\"} / 1024 / 1024",
     "legendFormat": "{{name}}: blockchain size"
    }
   ]
  },
  {
   "title": "Latest block information",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoind_blockchain_sync{name=\"btc1\",type=\"blocks\"}"
    }
   ]
  },
  {
   "title": "Mempool size in bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoind_mempool_size_bytes{name=\"btc1\"} / 1024.0",
     "legendFormat": "{{name}}: mempool size in KiB"
    }
   ]
  },
  {
   "title": "Transactions in mempool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoind_mempool_size_txs{name=\"btc1\"}",
     "legendFormat": "transactions in mempool {{name}}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoind_peers{name=\"btc1\",version=\"all\"}",
     "legendFormat": "{{name}: peers count"
    }
   ]
  },
  {
   "title": "Approximate fee per kilobyte by estimatesmartfee method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoind_fee{name=\"btc1\"}",
     "legendFormat": "{{name}}: target {{target}} with mode {{mode}}"
    }
   ]
  }
 ]
}